### ISSUE TITLE
Compilation Error due to Cpu::conditionPassed

### ISSUE THREAD

**Issue by electricalgorithm** [Rexagon/stm32-emulator#1]
I'm a newbie to the make/cmake processes. I tried these:

```bash
~$ git clone https://github.com/Rexagon/stm32-emulator.git
~$ cd stm32-emulator
~$ mkdir build && cd build
~$ sudo cmake ../
~$ sudo make install
```
But errors happened, need help.

**Comment by Rexagon** [comment]
Hi! Probably you should use `cmake --build . -- -j` instead of make install.
Can you please share the build log with errors?

P.S. This emulator was only written to learn how emulators work, so it is definitely not intended to be used (but maybe I will bring it to applicable condition when I have free time)

**Comment by electricalgorithm** [comment]
Edit: The problem is you've created Cpu::conditionPassed function with a parameter and in other classes, you've created a macro called CHECK_CONDITION that uses Cpu::conditionPassed function with no parameters.

Compiler gives an error which is "you have to add a parameter to use Cpu::conditionPassed."

I've tried it, and actually it is not a single or several errors to directly put here. Instead of it, I did paste it to pastebin.ubuntu. Here is the link of `sudo cmake --build . -- -j` command.

https://pastebin.ubuntu.com/p/4N56gm85js/

**Comment by electricalgorithm** [comment]
Thank you, it is solved. Since you pushed a new commit and solved this issue, I'm closing this.
